"""empty message

Revision ID: 5793238a9f84
Revises: 84baf2dde597
Create Date: 2017-10-14 14:33:41.136645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5793238a9f84'
down_revision = '84baf2dde597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column(
        'author', sa.String(length=42), nullable=True))
    op.drop_column('post', 'blog_ipns')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('blog_ipns', sa.TEXT(), nullable=True))
    op.drop_column('blog', 'author')
    # ### end Alembic commands ###
