"""empty message

Revision ID: 58ca9a289533
Revises: 5793238a9f84
Create Date: 2017-10-14 14:34:07.914614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ca9a289533'
down_revision = '5793238a9f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'blog_ipns')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('blog_ipns', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
