"""empty message

Revision ID: 84baf2dde597
Revises: 
Create Date: 2017-10-14 02:36:40.307799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84baf2dde597'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'key')
    # ### end Alembic commands ###
